swagger: "2.0"
info:
  title: Student database
  description: Student database
  version: 1.0.0
host: localhost:8080
basePath: /
schemes:
  - http
paths:
  /students:
    post:
      summary: Create a new student
      tags:
        - Students
      parameters:

